# Generated by Django 3.2.19 on 2023-05-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230517_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pk']},
        ),
    ]
