# Generated by Django 3.2.19 on 2023-05-17 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fruits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fruit",
            options={"ordering": ["name"]},
        ),
    ]
